### ISSUE TITLE
Opening a web application sometimes displays a "The project system has encountered an error"

### ISSUE THREAD

**Issue by srivatsn** [aspnet/Tooling#942]
_From @davkean on January 8, 2017 23:48_

Build: 26107.1.d15prel

I ran into this sometimes when opening a web application:

```
---------------------------
Microsoft Visual Studio
---------------------------
The project system has encountered an error.

Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'DotNetCoreWeb'.

A diagnostic log has been written to the following location: "C:\Users\davkean\AppData\Local\Temp\VsProjectFault_12bec44c-f230-4c32-8667-b0ff882c0c4b.failure.txt".

---------------------------
OK   
---------------------------
```

Stack:

```
=====================
1/9/2017 10:46:56 AM
Crippling
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'DotNetCoreWeb'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'DotNetCoreWeb'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================
1/9/2017 10:46:57 AM
Crippling
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'EditAndContinue'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'EditAndContinue'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================
1/9/2017 10:46:57 AM
Crippling
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'DotNetCoreWeb'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'DotNetCoreWeb'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================
1/9/2017 10:46:57 AM
Crippling
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'DotNetCoreWeb'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'DotNetCoreWeb'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================
1/9/2017 10:46:57 AM
Crippling
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'EditAndContinue'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'EditAndContinue'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================

```

_Copied from original issue: dotnet/roslyn-project-system#1103_

**Comment by srivatsn** [comment]
_From @attilah on January 9, 2017 23:52_

The same happened to me with build: 26109.0.d15rel. Previous RCs worked well.

Repro:
1. https://github.com/dotnet/orleans
2. Open vNext\src\Orleans.vNext.sln

**Comment by srivatsn** [comment]
_From @attilah on January 10, 2017 17:58_

If I removed the ```<ProjectCapability Include="EditAndContinue"/>``` from ```"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\Managed"\Microsoft.Managed.DesignTime.targets``` then the exception is not happening.

**Comment by srivatsn** [comment]
_From @333fred on January 12, 2017 23:52_

Fixed in #1141.

**Comment by srivatsn** [comment]
_From @davkean on January 12, 2017 23:54_

This is one is tracking DotNetWeb whcih isn't fixed. The EditAndContinue issue was fixed.

**Comment by davkean** [comment]
This is likely caused by a auto-load component that isn't dynamic. 

Give DotNetWeb is coming from a targets file - the capability is considered dynamic, and can run into these sorts of issues.

**Comment by davkean** [comment]
Here's the assert under dbg CPS bits:

![image](https://cloud.githubusercontent.com/assets/1103906/21949072/7199de1a-da43-11e6-9e38-8736106c3150.png)

**Comment by natemcmaster** [comment]
:bell: any status update on this? I'm still seeing this in RC.3.

 cc @vijayrkn @mlorbetske this is in aspnet/websdk

**Comment by vijayrkn** [comment]
Is the assert happening because of these Project Capability includes? 
https://github.com/aspnet/websdk/blob/dev/src/Web/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.targets#L28-L34 

What is the right place to include Capabilities (if not from the targets)?

cc @abpiskunov @BillHiebert

**Comment by abpiskunov** [comment]
Hm @BillHiebert  updated our autoload components to be dynamic lately and we should not have seen that again...

**Comment by natemcmaster** [comment]
I ran into the error with this solution: https://github.com/aspnet/SignalR/blob/7ec79bcd7c55cb2520883c08bfe2777ef9711c47/SignalR.sln

I was using VS 15.0.26127.0. It doesn't happen everytime...not sure how to make it repo consistently.

**Comment by davkean** [comment]
The exact error? Does it list the "Related Capabilities"?

**Comment by natemcmaster** [comment]
```
=====================
2/1/2017 11:16:32 AM
Crippling
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'DotNetCoreWeb'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project, and forces the project to be reloaded.  Potential capabilties involved: 'DotNetCoreWeb'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.RequestReloadForIncompatibleCapabilitiesAsync(IImmutableSet`1 capabilities)
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.CapabilityScopeRequirementState.<>c__DisplayClass8_0.<<InitialProjectReload>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================
```

**Comment by davkean** [comment]
@BillHiebert @abpiskunov Are we sure we have:

1) All the auto-load components and converted to dynamic
2) ProjectNode COM extensions

**Comment by BillHiebert** [comment]
Can you try a newer build. We did an insertion on the 27th, so most likely you need a build newer than 15.0.26127.0

**Comment by natemcmaster** [comment]
Seems to be okay in newer builds. 👌

**Comment by davkean** [comment]
I'm going to close this.

**Comment by xperiandri** [comment]
I have the same error when projects from the other folder are added to solutions

![default](https://cloud.githubusercontent.com/assets/2365592/24167451/77c9dae0-0e7f-11e7-8f56-0c12a9cad344.png)

```
=====================
21.03.2017 21:25:25
Crippling
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An element with the same key but a different value already exists. Key: System.Xml.XPath
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectBuildSubscriptionService.UpdateRuleSnapshotCore(IProjectVersionedValue`1 source, String ruleName, IRule rule, ImmutableDictionary`2 items, ImmutableDictionary`2 properties, ImmutableList`1 recentItemRenames, IProjectChangeDiff& diff)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectRuleSubscriptionServiceBase`1.UpdateSnapshotCoreAsync(TSource source, IImmutableSet`1 subscribedElements, IProjectVersionedValue`1 previousResult)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<UpdateSnapshotAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<>c__DisplayClass27_0.<<Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<<Initialize>b__27_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DataflowExtensions.<>c__DisplayClass23_0`2.<<CreateSelfFilteringTransformBlock>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: An element with the same key but a different value already exists. Key: System.Xml.XPath
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectBuildSubscriptionService.UpdateRuleSnapshotCore(IProjectVersionedValue`1 source, String ruleName, IRule rule, ImmutableDictionary`2 items, ImmutableDictionary`2 properties, ImmutableList`1 recentItemRenames, IProjectChangeDiff& diff)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectRuleSubscriptionServiceBase`1.UpdateSnapshotCoreAsync(TSource source, IImmutableSet`1 subscribedElements, IProjectVersionedValue`1 previousResult)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<UpdateSnapshotAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<>c__DisplayClass27_0.<<Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<<Initialize>b__27_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DataflowExtensions.<>c__DisplayClass23_0`2.<<CreateSelfFilteringTransformBlock>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================
```

**Comment by xperiandri** [comment]
Like in this `.sln`

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26228.4
MinimumVisualStudioVersion = 10.0.40219.1
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "src", "src", "{B0D50255-CBDC-40C4-8B85-94C43E4D3ECF}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{AD54301D-735E-4F26-9D6A-38986A32B183}"
	ProjectSection(SolutionItems) = preProject
		NuGet.config = NuGet.config
	EndProjectSection
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "HahaTaxi.Api", "src\HahaTaxi.Api\HahaTaxi.Api.csproj", "{3C8B317F-DD8B-4621-AD30-F64B548D1CD5}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "HahaTaxi.Data", "src\HahaTaxi.Data\HahaTaxi.Data.csproj", "{F34B9C8C-D5C6-4D70-91B8-514114B306F1}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "HahaTaxi.Logging", "src\HahaTaxi.Logging\HahaTaxi.Logging.csproj", "{7A596BAC-2490-4294-A34B-67AB483A3280}"
EndProject
Project("{00D1A9C2-B5F0-4AF3-8072-F6C62B433612}") = "HahaTaxi.Database", "src\HahaTaxi.Database\HahaTaxi.Database.sqlproj", "{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "HahaTaxi.SignalRClient", "src\HahaTaxi.SignalRClient\HahaTaxi.SignalRClient.csproj", "{54C347F5-C49A-4A87-A550-E1C934CCEDEC}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Swashbuckle.AspNetCore.Swagger", "..\..\GitHub\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.Swagger\Swashbuckle.AspNetCore.Swagger.csproj", "{2AE004A1-ADA3-4CD0-9D88-E4588D2EA1B0}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Swashbuckle.AspNetCore.SwaggerGen", "..\..\GitHub\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\Swashbuckle.AspNetCore.SwaggerGen.csproj", "{74F30AFC-2ED4-4C81-AE32-24141CCC242B}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Swashbuckle.AspNetCore.SwaggerUI", "..\..\GitHub\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerUI\Swashbuckle.AspNetCore.SwaggerUI.csproj", "{0438F390-BF4C-4B2F-8876-A242ADD19E21}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{3C8B317F-DD8B-4621-AD30-F64B548D1CD5}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{3C8B317F-DD8B-4621-AD30-F64B548D1CD5}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{3C8B317F-DD8B-4621-AD30-F64B548D1CD5}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{3C8B317F-DD8B-4621-AD30-F64B548D1CD5}.Release|Any CPU.Build.0 = Release|Any CPU
		{F34B9C8C-D5C6-4D70-91B8-514114B306F1}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{F34B9C8C-D5C6-4D70-91B8-514114B306F1}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{F34B9C8C-D5C6-4D70-91B8-514114B306F1}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{F34B9C8C-D5C6-4D70-91B8-514114B306F1}.Release|Any CPU.Build.0 = Release|Any CPU
		{7A596BAC-2490-4294-A34B-67AB483A3280}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{7A596BAC-2490-4294-A34B-67AB483A3280}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{7A596BAC-2490-4294-A34B-67AB483A3280}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{7A596BAC-2490-4294-A34B-67AB483A3280}.Release|Any CPU.Build.0 = Release|Any CPU
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}.Debug|Any CPU.Deploy.0 = Debug|Any CPU
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}.Release|Any CPU.Build.0 = Release|Any CPU
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F}.Release|Any CPU.Deploy.0 = Release|Any CPU
		{54C347F5-C49A-4A87-A550-E1C934CCEDEC}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{54C347F5-C49A-4A87-A550-E1C934CCEDEC}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{54C347F5-C49A-4A87-A550-E1C934CCEDEC}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{54C347F5-C49A-4A87-A550-E1C934CCEDEC}.Release|Any CPU.Build.0 = Release|Any CPU
		{2AE004A1-ADA3-4CD0-9D88-E4588D2EA1B0}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{2AE004A1-ADA3-4CD0-9D88-E4588D2EA1B0}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{2AE004A1-ADA3-4CD0-9D88-E4588D2EA1B0}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{2AE004A1-ADA3-4CD0-9D88-E4588D2EA1B0}.Release|Any CPU.Build.0 = Release|Any CPU
		{74F30AFC-2ED4-4C81-AE32-24141CCC242B}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{74F30AFC-2ED4-4C81-AE32-24141CCC242B}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{74F30AFC-2ED4-4C81-AE32-24141CCC242B}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{74F30AFC-2ED4-4C81-AE32-24141CCC242B}.Release|Any CPU.Build.0 = Release|Any CPU
		{0438F390-BF4C-4B2F-8876-A242ADD19E21}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{0438F390-BF4C-4B2F-8876-A242ADD19E21}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{0438F390-BF4C-4B2F-8876-A242ADD19E21}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{0438F390-BF4C-4B2F-8876-A242ADD19E21}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(NestedProjects) = preSolution
		{3C8B317F-DD8B-4621-AD30-F64B548D1CD5} = {B0D50255-CBDC-40C4-8B85-94C43E4D3ECF}
		{F34B9C8C-D5C6-4D70-91B8-514114B306F1} = {B0D50255-CBDC-40C4-8B85-94C43E4D3ECF}
		{7A596BAC-2490-4294-A34B-67AB483A3280} = {B0D50255-CBDC-40C4-8B85-94C43E4D3ECF}
		{C285C9DE-BE4A-4A7B-8387-920D5EE9BF0F} = {B0D50255-CBDC-40C4-8B85-94C43E4D3ECF}
		{54C347F5-C49A-4A87-A550-E1C934CCEDEC} = {B0D50255-CBDC-40C4-8B85-94C43E4D3ECF}
	EndGlobalSection
	GlobalSection(CodealikeProperties) = postSolution
		SolutionGuid = d1818a1b-51ed-4c07-8f41-441e0f4bdc1d
	EndGlobalSection
EndGlobal
```

Where SwashBuckle is located in the folder other that folder with `.sln` or subfolders

**Comment by 333fred** [comment]
@xperiandri this appears to be an unrelated issue. Can you please open a new issue on the project system repo [here](https://github.com/dotnet/roslyn-project-system)?

**Comment by xperiandri** [comment]
OK, I will
